Dockerfile Verification Results
Date: 2025-10-19T19:07:34.394669
======================================================================

Total: 6
Valid: 2
Invalid: 4
Success Rate: 33.3%

======================================================================

[VALID] leethomason/tinyxml2
  Time: 5.1s
  Message: Build successful

[VALID] dvyshnavi15/helloworld
  Time: 2.4s
  Message: Build successful

[INVALID] ImageMagick/ImageMagick
  Time: 0.0s
  Message: DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/bui

[INVALID] DaveGamble/cJSON
  Time: 0.0s
  Message: DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/bui

[INVALID] curl/curl
  Time: 0.1s
  Message: DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/bui

[INVALID] nothings/stb
  Time: 0.0s
  Message: DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/bui
