#!/usr/bin/env python3
# Simplified runtest.py - 3 simple steps only
# Copyright (2025) Bytedance Ltd. and/or its affiliates 

import subprocess
import sys
import os

def run_c_tests():
    """
    Simplified runtest logic:
    1. Check essential files only (build system ready?)
    2. Run test command (based on build system)
    3. Check result (pass/fail only)
    """
    
    # ==========================================
    # Step 1: Check essential files
    # ==========================================
    
    # 🥇 CMake build?
    if os.path.exists('/repo/build/CMakeCache.txt'):
        print('Found CMake build configuration.')
        
        # Essential file: Makefile (generated by cmake)
        if not os.path.exists('/repo/build/Makefile'):
            print('❌ Error: CMake configured but Makefile not found.')
            print('Please run: cd /repo/build && cmake ..')
            sys.exit(1)
        
        print('✅ Essential files found (Makefile exists).')
        test_command = 'ctest --output-on-failure || make test'
        test_cwd = '/repo/build'
    
    # 🥈 Makefile build?
    elif os.path.exists('/repo/Makefile'):
        print('Found Makefile build.')
        print('✅ Essential files found (Makefile exists).')
        test_command = 'make test || make check'
        test_cwd = '/repo'
    
    # ❌ No build system
    else:
        print('No build system detected.')
        
        # Check if this is a simple project (just .c files)
        if os.path.exists('/repo/CMakeLists.txt'):
            print('❌ Error: CMakeLists.txt found but not configured.')
            print('Please run: mkdir -p /repo/build && cd /repo/build && cmake ..')
            sys.exit(1)
        elif os.path.exists('/repo/configure'):
            print('❌ Error: configure script found but not run.')
            print('Please run: cd /repo && ./configure')
            sys.exit(1)
        else:
            # Very simple project - no build needed
            print('Simple project detected. No tests to run.')
            print('Congratulations, you have successfully configured the environment!')
            sys.exit(0)
    
    # ==========================================
    # Step 2: Run test command
    # ==========================================
    
    print(f'\nRunning tests: {test_command}')
    print('-' * 60)
    
    result = subprocess.run(
        test_command,
        cwd=test_cwd,
        shell=True,
        capture_output=True,
        text=True
    )
    
    # ==========================================
    # Step 3: Check result
    # ==========================================
    
    if result.returncode == 0:
        # Success!
        print('-' * 60)
        print('✅ Tests passed!')
        print('\nCongratulations, you have successfully configured the environment!')
        print('\nTest output:')
        print(result.stdout)
        sys.exit(0)
    else:
        # Failed
        print('-' * 60)
        print('❌ Tests failed!')
        print('\nPlease fix the errors below:')
        print('\nStdout:')
        print(result.stdout)
        print('\nStderr:')
        print(result.stderr)
        sys.exit(result.returncode)

if __name__ == '__main__':
    run_c_tests()

